version: "3.9"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend